'use strict';
// Event and lifecycle checks for the compiled page; this shim does not render CSS.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const page=fs.readFileSync(__dirname+'/academia.html','utf8');
let unpacked=page;for(const [name,marker] of [['SRC','__SRC_JSON__'],['ART_META','__ART_JSON__'],['KID_SPRITES','__KID_JSON__'],['PET_SPRITES','__PET_JSON__'],['MAP_DATA','__MAP_JSON__'],['CHALLENGES','__CHALLENGES_JSON__']])unpacked=unpacked.replace(new RegExp('^const '+name+' = [^\\n]*;$','m'),'const '+name+' = '+marker+';');assert.ok(unpacked===fs.readFileSync(__dirname+'/plantilla.html','utf8'),'compiled artifact must match the current template');
const script=page.match(/<script>([\s\S]*)<\/script>/)[1];
async function launch({width=400,height=820,playHeight=570,touch=true,reduced=false,saved=null}={}){
 const errors=[],nodes={},animations=[],timers=new Map(),hold=[],events={},audio={contexts:0,notes:[]},draws=[];let now=0,nextTimer=1,raf,observer,seed=123456;const seededMath=Object.create(Math);seededMath.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
 const context2d=new Proxy({createRadialGradient:()=>({addColorStop(){}}),createLinearGradient:()=>({addColorStop(){}}),drawImage:(img,...args)=>{assert.ok(img,'drawImage needs a loaded image');assert.ok(args.every(n=>Number.isFinite(n)),'drawImage coordinates must be finite');draws.push({src:img?.src,args});},measureText:t=>({width:String(t).length*7}),getImageData:(x,y,w,h)=>({data:new Uint8ClampedArray(w*h*4)})},{get:(o,k)=>k in o?o[k]:(()=>{})});
 class Element{
  constructor(tag='div'){
   this.tagName=tag.toUpperCase();this.children=[];this.hidden=false;this._text='';this.dataset={};this.style={properties:{},setProperty(k,v){this.properties[k]=v;}};this.events={};this.attributes={};this.width=100;this.height=100;this.isConnected=true;this.parentElement=null;this.disabled=false;
   this.classes=new Set();this.classList={add:(...a)=>a.forEach(x=>this.classes.add(x)),remove:(...a)=>a.forEach(x=>this.classes.delete(x)),contains:a=>this.classes.has(a),toggle:(a,b)=>{if(b===undefined)b=!this.classes.has(a);b?this.classes.add(a):this.classes.delete(a);return b;}};
  }
  set className(v){this.classes=new Set(v.split(/\s+/).filter(Boolean));}get className(){return [...this.classes].join(' ');}
  set textContent(v){this._text=String(v);this.replaceChildren();}get textContent(){return this._text+this.children.map(n=>n.textContent).join('');}
  append(...a){for(const child of a){child.parentElement=this;this.children.push(child);}}replaceChildren(...a){for(const child of this.children){child.parentElement=null;child.isConnected=false;}this.children=[];for(const child of a)child.isConnected=true;this.append(...a);}
  remove(){if(this.parentElement)this.parentElement.children=this.parentElement.children.filter(c=>c!==this);this.isConnected=false;}
  addEventListener(name,fn){(this.events[name]??=fn);}setAttribute(name,val){this.attributes[name]=String(val);if(name==='class')this.className=val;}getAttribute(name){return this.attributes[name];}
  removeAttribute(name){delete this.attributes[name];if(name==='id')delete this.id;}
  cloneNode(deep){const copy=new Element(this.tagName);for(const key of ['id','src','alt','hidden','_text','disabled','tabIndex','href'])if(this[key]!==undefined)copy[key]=this[key];copy.className=this.className;copy.attributes={...this.attributes};if(deep)copy.append(...this.children.map(n=>n.cloneNode(true)));return copy;}
  animate(frames,options){const animation={frames,options,cancelled:false,cancel(){this.cancelled=true;timers.delete(id);}};animations.push(animation);const id=nextTimer++;timers.set(id,{at:now+options.duration,fn:()=>animation.onfinish?.()});return animation;}
  focus(){document.activeElement=this;this.events.focus?.();}click(){if(!this.disabled)this.events.click?.({target:this});}
  matches(selector){return selector.split(',').some(selector=>{selector=selector.trim();if(selector.includes(':not(:disabled)')&&this.disabled)return false;selector=selector.replace(':not(:disabled)','');const attr=selector.match(/\[([^=\]]+)(?:="?([^"\]]+)"?)?\]/);if(attr){let val=attr[1].startsWith('data-')?this.dataset[attr[1].slice(5)]:this.getAttribute(attr[1]);if(attr[1]==='tabindex')val=this.tabIndex??val;if(attr[1]==='href')val=this.href;if(val===undefined||attr[2]!==undefined&&String(val)!==attr[2])return false;selector=selector.replace(attr[0],'');}if(selector.startsWith('.'))return this.classList.contains(selector.slice(1));if(selector.startsWith('#'))return this.id===selector.slice(1);return !selector||this.tagName===selector.toUpperCase();});}
  closest(selector){for(let n=this;n;n=n.parentElement)if(n.matches(selector))return n;return null;}getClientRects(){for(let n=this;n;n=n.parentElement)if(n.hidden)return [];return [1];}
  querySelectorAll(selector){const found=[];for(const child of this.children){if(child.matches(selector))found.push(child);found.push(...child.querySelectorAll(selector));}return found;}querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
  getContext(){return context2d;}setPointerCapture(){}scrollIntoView(){}
  getBoundingClientRect(){return {left:0,top:0,width,height:playHeight};}
 }
 const document={hidden:false,body:new Element(),getElementById:id=>document.body.querySelector('#'+id)||nodes[id]||(nodes[id]=new Element(['view','mini'].includes(id)?'canvas':'div')),createElement:t=>new Element(t),createElementNS:(ns,t)=>new Element(t),querySelectorAll:selector=>selector==='[data-hold]'?hold:document.body.querySelectorAll(selector),addEventListener(){}};
 const overlay=document.getElementById('overlay');overlay.hidden=true;document.getElementById('toast').hidden=true;
 const gameWindow=document.getElementById('game-window'),header=document.getElementById('window-header'),stage=document.getElementById('stage');stage.tabIndex=-1;header.append(document.getElementById('window-title'),document.getElementById('window-wallet'),document.getElementById('overlay-close'));gameWindow.append(header,stage,document.getElementById('overlay-back'));overlay.append(gameWindow);document.body.append(overlay);
 for(const id of ['overlay-close','overlay-back','bag','gestures','objectives-toggle','clock-hud','settings'])document.getElementById(id).tagName='BUTTON';
 for(const key of ['left','right','run','drop','jump']){const button=new Element('button');button.dataset.hold=key;hold.push(button);}
 const storage={value:saved,getItem(){return this.value;},setItem(k,v){this.value=v;}};
 const c=vm.createContext({Math:seededMath,document,innerWidth:width,innerHeight:height,devicePixelRatio:2,navigator:{maxTouchPoints:touch?5:0},localStorage:storage,
  console:{error:e=>errors.push(String(e))},AudioContext:class{constructor(){audio.contexts++;this.currentTime=0;this.state='running';this.destination={};}createOscillator(){const note={};audio.notes.push(note);return {type:'',frequency:{setValueAtTime:f=>note.frequency=f},connect(){},start:at=>note.at=at,stop(){}};}createGain(){return {gain:{setValueAtTime(){},linearRampToValueAtTime:v=>audio.volume=v,exponentialRampToValueAtTime(){}},connect(){}};}},matchMedia:q=>({matches:q.includes('reduced')?reduced:touch,addEventListener(){}}),performance:{now:()=>now},
  requestAnimationFrame:f=>{raf=f;return 1;},ResizeObserver:class{constructor(cb){observer=cb;}observe(){}},
  setTimeout:(fn,delay)=>{const id=nextTimer++;timers.set(id,{fn,at:now+delay});return id;},clearTimeout:id=>timers.delete(id),
  Image:class{constructor(){this.width=406;this.height=314;}set src(s){this.onload?.();}},ImageData:class{},Uint8Array,Float32Array,Uint8ClampedArray});
 c.window=c;c.addEventListener=(name,fn)=>events[name]=fn;vm.runInContext(script,c);await new Promise(setImmediate);
 const runTime=ms=>{const until=now+ms;for(;;){const [id,entry]=[...timers].filter(([,t])=>t.at<=until).sort((a,b)=>a[1].at-b[1].at)[0]||[];if(!entry)break;now=entry.at;timers.delete(id);entry.fn();}now=until;};
 const frames=n=>{for(let i=0;i<n;i++){now+=1000/60;draws.length=0;raf(now);}};
 assert.deepEqual(errors,[]);assert.equal(nodes.loading.hidden,true);assert.ok(raf);
 return {game:c.Academia,nodes,hold,errors,storage,runTime,frames,audio,draws,animations,active:()=>document.activeElement,key:(key,kind='keydown',modifiers={})=>{const target=document.activeElement||nodes.view;let prevented=false;const event={key,repeat:false,preventDefault(){prevented=true;},target,...modifiers};events[kind](event);if(kind==='keydown'&&!prevented&&key==='Enter'&&target.tagName==='BUTTON')target.click();},resize:(w,h,ph)=>{width=w;height=h;playHeight=ph;c.innerWidth=w;c.innerHeight=h;observer();}};
}
function findText(root,text){if(root.textContent===text && root.tagName==='BUTTON')return root;for(const child of root.children||[]){const found=findText(child,text);if(found)return found;}return null;}
(async()=>{
 for(const touch of [false,true]){
  const app=await launch({touch}),{game,nodes,runTime}=app;
  assert.equal(nodes.objective.hidden,false);assert.equal(nodes['objectives-toggle'].getAttribute('aria-expanded'),'true');
  assert.equal(nodes.toast.hidden,false);assert.equal(nodes.toast.textContent.includes(touch?'toca Hablar':'pulsa E'),true);
  runTime(4599);assert.equal(nodes.toast.classList.contains('fading'),false);
  runTime(1);assert.equal(nodes.toast.classList.contains('fading'),true);assert.equal(nodes.toast.hidden,false);
  runTime(400);assert.equal(nodes.toast.hidden,true);
  assert.equal(nodes.view.width,600);assert.equal(nodes.view.height,855,'buffer uses play height and capped DPR');
  app.resize(820,400,250);assert.equal(nodes.view.width,1230);assert.equal(nodes.view.height,375);
  app.resize(400,820,570);
  game.interact(game.map.entities.find(e=>e.id==='estela'));assert.equal(game.state.flags.metEstela,true);assert.equal(nodes.objective.hidden,true);
  game.closeOverlay();assert.equal(nodes.objective.hidden,true,'closing dialogue keeps objectives collapsed');
  nodes['objectives-toggle'].onclick();assert.equal(nodes.overlay.hidden,false);assert.equal(nodes['window-title'].textContent,'Objetivos');findText(nodes.stage,'Mostrar objetivo en el mapa').click();assert.equal(nodes.objective.hidden,false);assert.equal(nodes['objectives-toggle'].getAttribute('aria-expanded'),'true');
  game.showSettings();assert.equal(nodes.objective.hidden,true);game.closeOverlay();assert.equal(nodes.objective.hidden,false,'panel preserves manual disclosure');
  const restored=await launch({touch,saved:app.storage.value});assert.equal(restored.nodes.objective.hidden,true,'first contact persists');assert.equal(restored.nodes.toast.hidden,true,'welcome is not repeated');
  game.interact(game.map.entities.find(e=>e.id==='guide'));assert.equal(nodes.overlay.hidden,false);assert.ok(nodes.stage.children[0].children.some(n=>n.textContent==='Camino de estrellas'));game.closeOverlay();
  for(const action of ['travel','shop','bank','reading','arcade','board','garden','practice']){game.station(action);assert.equal(nodes.overlay.hidden,false,action);game.closeOverlay();}
  // Cancelling a held direction must release it, including while the device rotates.
  const right=app.hold.find(b=>b.dataset.hold==='right');app.frames(3);const x=game.player.x;
  right.events.pointerdown({preventDefault(){},pointerId:1});app.frames(40);assert.ok(game.player.x>x+20);assert.ok(right.classList.contains('pressed'));
  right.events.pointercancel();app.frames(30);const stopped=game.player.x;app.frames(30);assert.ok(Math.abs(game.player.x-stopped)<1);assert.equal(right.classList.contains('pressed'),false);
  const jump=app.hold.find(b=>b.dataset.hold==='jump');Object.assign(game.player,{x:1860,y:440,ground:true,energy:1});app.resize(400,820,570);
  jump.events.pointerdown({preventDefault(){},pointerId:2});
  for(let i=0;i<70;i++){app.frames(1);const v=game.viewport;assert.ok((game.player.y-100-v.y)*v.zoom>=-1e-8,'head remains visible through a charged jump: '+JSON.stringify({i,y:game.player.y,v}));assert.ok((game.player.y-v.y)*v.zoom<=v.height,'feet remain in play area');}
  jump.events.pointerup();
  game.showSettings();findText(nodes.stage,'Reiniciar progreso').events.click();findText(nodes.stage,'Sí, reiniciar').events.click();assert.equal(nodes.objective.hidden,false);assert.equal(Boolean(game.state.flags.metEstela),false);
  assert.deepEqual(app.errors,[]);console.log('✓ compiled UI: '+(touch?'touch':'keyboard')+', toast timing, objectives, save/restore, controls, resize and panels');
 }
 const reduced=await launch({reduced:true});reduced.runTime(4600);assert.equal(reduced.nodes.toast.hidden,true);console.log('✓ reduced motion dismisses the welcome without waiting for a fade');
 const replacement=await launch();replacement.runTime(4000);replacement.game.loadMap({id:'second',title:'Otro mapa',unit:'CH',size:[20,9],floors:[{x:0,y:7.8,w:20,h:1.2,sprite:'suelo'}],entities:[{id:'second-spawn',type:'spawn',x:2,y:7.8}]});replacement.runTime(1000);assert.equal(replacement.nodes.toast.hidden,false);assert.equal(replacement.nodes.toast.textContent,'Otro mapa');replacement.runTime(2900);assert.equal(replacement.nodes.toast.hidden,true);console.log('✓ a replacement toast clears the previous dismissal');

 for(const reducedMotion of [false,true]){
  const app=await launch({width:1600,height:900,playHeight:820,touch:false,reduced:reducedMotion}),{game,nodes}=app;
  for(const e of game.map.entities.filter(e=>['station','portal','npc','sign','secret'].includes(e.type))){
   // Cross the station under real tick() movement, then interact using the keyboard event.
   if(e.type==='secret')game.state.revealed.push(e.id);
   Object.assign(game.player,{x:e.x-135,y:e.y,vx:0,vy:0,ground:true});app.key('ArrowRight');app.frames(170);app.key('ArrowRight','keyup');
   assert.equal(nodes.overlay.hidden,true,'passing '+e.id+' must not open a panel');assert.equal(game.treasure,null);
   Object.assign(game.player,{x:e.x,y:e.y,vx:0,vy:0,ground:true});app.frames(3);app.key('e');assert.equal(nodes.overlay.hidden,false,'E opens '+e.id);game.closeOverlay();
  }
  console.log('✓ E-only interaction at every station, portal, NPC, sign and telescope ('+(reducedMotion?'reduced':'animated')+')');
 }
 const chestApp=await launch({width:1600,height:900,playHeight:820,touch:false}),{game:cg,nodes:cn}=chestApp;
 const chest=cg.map.entities.find(e=>e.id==='high-chest');Object.assign(cg.player,{x:chest.x-55,y:chest.y,vx:0,vy:0,ground:true});chestApp.frames(3);
 assert.equal(cg.state.revealed.includes(chest.id),true,'secret proximity only reveals');assert.equal(cn.overlay.hidden,true);assert.equal(chestApp.audio.contexts,0);
 chestApp.key('Enter');assert.ok(cg.treasure);assert.equal(cg.state.tokens,75);assert.equal(cg.state.items.filter(i=>i.id==='medallon').length,1);assert.equal(cn.overlay.hidden,true);assert.equal(chestApp.audio.contexts,1);assert.equal(chestApp.audio.notes.length,0);
 const chestX=cg.player.x,baseZoom=cg.viewport.zoom;chestApp.key('ArrowRight');chestApp.frames(20);chestApp.key('e');assert.ok(cg.treasure,'anticipation cannot be skipped');assert.equal(cg.player.x,chestX,'cinematic locks control');assert.ok(cg.viewport.zoom>baseZoom);
 chestApp.frames(150);assert.equal(cn.treasure.hidden,false);assert.equal(cg.treasure.banner,true);assert.equal(chestApp.audio.notes.length,5);assert.ok(chestApp.audio.volume<=.02);assert.equal(cn['treasure-title'].textContent,'¡Conseguiste: Medallón del cielo!');assert.equal(cn['treasure-tokens'].textContent,'+15 fichas');
 const up=cg.viewport.zoom;chestApp.key('e');assert.equal(cg.treasure,null);assert.equal(cn.treasure.hidden,true);chestApp.frames(80);assert.ok(cg.viewport.zoom<up);chestApp.key('Enter');assert.equal(cg.state.tokens,75);assert.equal(cg.state.items.length,1);assert.equal(cg.treasure,null);cg.closeOverlay();
 const savedChest=await launch({saved:chestApp.storage.value});assert.equal(savedChest.game.state.chests.includes(chest.id),true);assert.equal(savedChest.game.state.tokens,75);
 console.log('✓ chest timing, control lock, fanfare after input, banner, camera return, persistence and rewards once');
 const short=await launch();const sc=short.game.map.entities.find(e=>e.id==='high-chest');Object.assign(short.game.player,{x:sc.x,y:sc.y,ground:true});short.frames(3);short.key('e');short.frames(70);short.key('e');assert.equal(short.game.treasure,null);assert.equal(short.game.state.tokens,75);console.log('✓ E can skip once the item appears');
 const quiet=await launch({reduced:true});quiet.game.state.settings.sound=false;const qc=quiet.game.map.entities.find(e=>e.id==='high-chest');Object.assign(quiet.game.player,{x:qc.x,y:qc.y,ground:true});quiet.frames(3);const qz=quiet.game.viewport.zoom;quiet.nodes['action-touch'].onclick();quiet.frames(1);assert.equal(quiet.nodes.treasure.hidden,false);assert.equal(quiet.game.viewport.zoom,qz);assert.equal(quiet.audio.contexts,0);quiet.nodes['treasure-close'].onclick();assert.equal(quiet.game.treasure,null);assert.equal(quiet.game.state.tokens,75);console.log('✓ reduced chest swaps directly to banner, tap closes, sound toggle mutes');
 const locked=await launch();const lc=locked.game.map.entities.find(e=>e.id==='spark-chest');Object.assign(locked.game.player,{x:lc.x,y:lc.y,ground:true});locked.frames(3);locked.key('e');assert.equal(locked.nodes.overlay.hidden,false);assert.equal(locked.game.treasure,null);assert.equal(locked.game.state.tokens,60);locked.game.closeOverlay();locked.game.state.sparks.push(...locked.game.map.entities.filter(e=>e.type==='collectible').map(e=>e.id));locked.key('e');assert.equal(locked.game.state.tokens,80);locked.frames(180);locked.nodes['treasure-close'].onclick();assert.equal(locked.game.state.chests.filter(id=>id===lc.id).length,1);console.log('✓ locked chest hint, all twelve sparks unlock, touch dismisses');
 const prefs=await launch();prefs.game.showSettings();const prefCard=prefs.nodes.stage.children[0],soundLabel=prefCard.children.find(n=>n.children?.some(c=>c.textContent==='Sonido de los tesoros')),motionLabel=prefCard.children.find(n=>n.children?.some(c=>c.textContent==='Reducir movimiento'));assert.ok(soundLabel&&motionLabel);const soundInput=soundLabel.children.find(n=>n.tagName==='INPUT'),motionInput=motionLabel.children.find(n=>n.tagName==='INPUT');soundInput.checked=false;soundInput.events.change();motionInput.checked=true;motionInput.events.change();assert.equal(prefs.game.reducedMotion,true);prefs.game.closeOverlay();const prefRestored=await launch({saved:prefs.storage.value});assert.equal(prefRestored.game.state.settings.sound,false);assert.equal(prefRestored.game.reducedMotion,true);console.log('✓ sound and reduced-motion controls persist');
 const moving=await launch({width:1600,height:900,playHeight:820,touch:false});const starts=new Map(moving.game.classmates.map(c=>[c.id,c.x])),wandered=new Set();for(let minuteStep=0;minuteStep<60;minuteStep++){moving.frames(60);for(const c of moving.game.classmates)if(Math.abs(c.x-starts.get(c.id))>20)wandered.add(c.id);}assert.ok(wandered.has('benja') && wandered.has('tomas'),'both upstairs classmates wander between their own destinations');for(const c of moving.game.classmates){assert.ok(c.x>=c.zone[0]*100-1 && c.x<=c.zone[1]*100+1);assert.ok(Math.abs(c.y-(c.id==='benja'||c.id==='tomas'?440:780))<1e-8);}console.log('✓ classmates stay on their own floor and within their wing');
 for(const [width,height,playHeight,touch] of [[1600,900,820,false],[1024,768,606,true],[400,820,570,true],[820,400,250,true]]){const device=await launch({width,height,playHeight,touch});device.frames(5);const v=device.game.viewport;assert.equal(v.width,width);assert.equal(v.height,playHeight);assert.ok((device.game.player.y-v.y)*v.zoom<playHeight);assert.equal(device.nodes.view.width,Math.round(width*1.5));assert.deepEqual(device.errors,[]);}console.log('✓ desktop, tablet touch, phone portrait and landscape canvas/camera sizes');
 // Game menus: assert visible states and exercise the same handlers used by keyboard/touch.
 const shopApp=await launch({width:1600,height:900,touch:false}),{game:sg,nodes:sn}=shopApp;
 sg.showShop();assert.equal(sn['window-title'].textContent,'Puesto del Mercader');assert.equal(sn.overlay.getAttribute('aria-labelledby'),'window-title');assert.equal(sn['window-wallet'].hidden,false);
 const slots=sn.stage.querySelectorAll('.item-slot');assert.equal(slots.length,6);assert.equal(slots[0].getAttribute('aria-pressed'),'true');
 slots[2].click();assert.equal(slots[2].getAttribute('aria-pressed'),'true');assert.ok(sn.stage.querySelector('.merchant-bubble').textContent.includes('¡Nunca te perderás!'));
 const buy=sn.stage.querySelector('[data-action="buy"]');assert.equal(buy.disabled,false);assert.equal(buy.textContent,'Comprar25');buy.click();assert.equal(sg.state.tokens,35);assert.equal(sg.state.items.filter(i=>i.id==='brujula').length,1);assert.equal(sn.stage.querySelector('.owned-stamp').textContent,'En tu mochila');assert.equal(sn.stage.querySelector('[data-action="buy"]'),null);slots[2].click();assert.equal(sg.state.tokens,35,'repeat tap cannot buy an owned item');assert.ok(sn.stage.querySelector('.merchant-bubble').textContent.includes('¡Gracias!'));assert.ok(shopApp.animations.length>0,'buy animates an item toward the HUD');shopApp.runTime(400);assert.equal(sn['window-wallet'].children[1].textContent,'35');
 slots[3].click();const poor=sn.stage.querySelector('[data-action="buy"]');assert.equal(poor.disabled,true);assert.equal(poor.textContent,'Te faltan 5 fichas');poor.click();assert.equal(sg.state.tokens,35);assert.equal(sg.state.items.length,1);
 shopApp.key('ArrowRight');assert.equal(slots[4].getAttribute('aria-pressed'),'true');shopApp.key('e');assert.equal(sg.state.tokens,20);assert.equal(sg.state.items.length,2);shopApp.key('Escape');assert.equal(sn.overlay.hidden,true);assert.equal(sn.view,shopApp.active(),'Escape returns focus to the canvas');
 sg.showBag();assert.equal(sn.stage.querySelectorAll('.item-slot').length,12);assert.equal(sn.stage.querySelectorAll('.item-slot').filter(n=>!n.disabled).length,2);findText(sn.stage,'Vender · 12 fichas').click();assert.equal(sg.state.tokens,32);assert.equal(sg.state.items.some(i=>i.id==='brujula'),false);shopApp.key('q');assert.equal(sn.overlay.hidden,true);
 sg.showShop();shopApp.resize(400,820,570);shopApp.key('ArrowDown');assert.equal(sn.stage.querySelectorAll('.item-slot')[2].getAttribute('aria-pressed'),'true','grid navigation follows the phone two-column layout after rotation');sg.closeOverlay();
 console.log('✓ shop selection, prices, purchase, duplicate protection, insufficient balance, owned stamp, sale, rotation and E / Esc / Q');

 const messages=await launch({touch:true}),{game:mg,nodes:mn}=messages;const sparkChest=mg.map.entities.find(e=>e.id==='spark-chest');mg.state.sparks.push('spark-1','spark-2');mg.interact(sparkChest);
 assert.equal(mn.overlay.dataset.mode,'dialogue');assert.equal(mn.overlay.getAttribute('aria-labelledby'),'message-title');assert.equal(mn.stage.querySelectorAll('.spark-row')[0].children.length,12);assert.equal(mn.stage.querySelectorAll('.spark-row')[0].children.filter(n=>n.classList.contains('lit')).length,2);
 const line=mn.stage.querySelector('.message-text'),full=line.getAttribute('aria-label');assert.ok(line.textContent.length<full.length);messages.key('x');assert.equal(line.textContent,full);assert.equal(mn.overlay.hidden,false,'first key only completes the text');mn.stage.querySelector('.message-next').focus();messages.key('x');assert.equal(mn.overlay.hidden,true,'next key advances the short message, including with the arrow focused');
 mg.interact(mg.map.entities.find(e=>e.id==='estela'));const first=mn.stage.querySelector('.message-text');messages.key('e');assert.equal(first.textContent,first.getAttribute('aria-label'));messages.key('Enter');assert.notEqual(mn.stage.querySelector('.message-text').getAttribute('aria-label'),first.getAttribute('aria-label'));messages.runTime(1500);const auto=mn.stage.querySelector('.message-text');assert.equal(auto.textContent,auto.getAttribute('aria-label'),'typing completes quickly without input');mn['action-touch'].onclick();assert.notEqual(mn.stage.querySelector('.message-text'),auto,'touch action advances NPC dialogue');mg.closeOverlay();
 mg.state.flags.welcomed=true;mg.interact(mg.map.entities.find(e=>e.id==='estela'));assert.ok(mn.stage.querySelector('.message-choices'));messages.key(' ');messages.key('ArrowDown');messages.key('e');assert.equal(mn.overlay.hidden,true);assert.equal(mg.state.flags.travelReady,false,'stacked NPC choices retain their branch');
 mg.interact(mg.map.entities.find(e=>e.id==='guide'));messages.key('Escape');messages.runTime(2000);assert.equal(mn.overlay.hidden,true,'closed messages cannot restart from typing timers');
 console.log('✓ bottom message box, twelve-spark row, typewriter, any-key completion/advance, touch advance, NPC choices and timer cleanup');

 const bankApp=await launch({touch:false}),{game:bg,nodes:bn}=bankApp;bg.showBank();const amount=bn.stage.querySelector('input');assert.equal(amount.value,'10');findText(bn.stage,'+').click();assert.equal(amount.value,'11');findText(bn.stage,'−').click();assert.equal(amount.value,'10');findText(bn.stage,'5').click();assert.equal(amount.value,'5');findText(bn.stage,'Todo').click();assert.equal(amount.value,'60');findText(bn.stage,'Depositar').click();assert.equal(bg.state.tokens,0);assert.equal(bg.state.bank.balance,60);bankApp.runTime(400);assert.equal(bn.stage.querySelectorAll('.vault-column')[0].querySelector('strong').textContent,'0');assert.equal(bn.stage.querySelectorAll('.vault-column')[1].querySelector('strong').textContent,'60');
 findText(bn.stage,'10').click();findText(bn.stage,'Retirar').click();assert.equal(bg.state.tokens,10);assert.equal(bg.state.bank.balance,50);amount.value='2.5';findText(bn.stage,'Depositar').click();assert.equal(bg.state.tokens,10);amount.value='999';findText(bn.stage,'Retirar').click();assert.equal(bg.state.bank.balance,50);assert.ok(bn.stage.querySelector('.week-dial').getAttribute('aria-label').includes('semana'));
 bg.state.settings.testMode=true;bg.showBank();findText(bn.stage,'Avanzar una semana').click();assert.equal(bg.state.bank.balance,52);assert.equal(bg.state.tokens,10);bn['overlay-back'].onclick();assert.equal(bn.overlay.hidden,true);
 console.log('✓ bank stepper, 5 / 10 / Todo, transfers, count roll, invalid amount, weekly dial, interest test mode and Back');

 const menus=await launch({width:1024,height:768,touch:true}),{game:ug,nodes:un}=menus;ug.showClock();assert.equal(un.stage.querySelectorAll('.clock-piece').length,8);menus.key('ArrowRight');assert.ok(un.stage.textContent.includes('Pronto'));ug.state.pieces.push('chapter-2');ug.showClock();assert.ok(un.stage.querySelectorAll('.clock-piece')[1].classList.contains('owned'));ug.closeOverlay();
 ug.showTravel();assert.equal(un.stage.querySelectorAll('.postcard').length,8);const travelLink=un.stage.querySelector('a');assert.ok(travelLink.href.includes('4rjPdYSBxNpHofQ8u5MU7s'));assert.equal(un.stage.querySelector('.postcard').querySelector('img').src.startsWith('data:image/webp'),true);menus.key('d');assert.equal(un.stage.querySelector('a'),null);assert.ok(un.stage.querySelector('.travel-bottom').textContent.includes('Pronto'));menus.key('Escape');
 ug.showReading();const bookText=un.stage.querySelector('.book-page').textContent;findText(un.stage,'Página siguiente →').click();assert.notEqual(un.stage.querySelector('.book-page').textContent,bookText);assert.equal(ug.state.sparks.filter(id=>id==='reading-spark').length,1);ug.closeOverlay();ug.showReading();assert.equal(ug.state.sparks.filter(id=>id==='reading-spark').length,1);ug.closeOverlay();
 ug.station('telescope');menus.runTime(1500);menus.key('Enter');assert.ok(un.stage.querySelector('.sky-map'));assert.equal(ug.state.sparks.filter(id=>id==='sky-spark').length,1);ug.closeOverlay();ug.showObjectives();assert.equal(un.stage.querySelectorAll('li').length,6);ug.closeOverlay();
 ug.showSettings();menus.key('Tab');assert.equal(menus.active(),un['overlay-close']);menus.key('Tab', 'keydown', {shiftKey:true});assert.equal(menus.active(),un['overlay-back']);menus.key('Tab');assert.equal(menus.active(),un['overlay-close']);
 const touchToggle=un.stage.querySelectorAll('input').find(n=>n.getAttribute('aria-label')==='Controles táctiles');touchToggle.checked=false;touchToggle.events.change();ug.closeOverlay();const restoredTouch=await launch({saved:menus.storage.value});assert.equal(restoredTouch.game.state.settings.touchControls,false);
 console.log('✓ clock selection, travel postcards and locks, reading pages and unique rewards, sky chart, objectives, Tab focus trap and touch preference save');

 const noMotion=await launch({reduced:true,touch:false}),{game:rg,nodes:rn}=noMotion;rg.state.settings.sound=false;rg.showShop();const notes=noMotion.audio.notes.length;rn.stage.querySelector('[data-action="buy"]').click();assert.equal(rg.state.tokens,50);assert.equal(rn['window-wallet'].children[1].textContent,'50','reduced motion updates counts immediately');assert.equal(noMotion.audio.notes.length,notes,'sound toggle mutes menu sounds');assert.equal(noMotion.animations.length,0,'reduced motion skips item flight');rg.closeOverlay();rg.interact(rg.map.entities.find(e=>e.id==='guide'));const text=rn.stage.querySelector('.message-text');assert.equal(text.textContent,text.getAttribute('aria-label'));noMotion.key('e');assert.equal(rn.overlay.hidden,true,'reduced-motion text needs only the advance input');
 console.log('✓ reduced-motion instant counts and message text, and muted menu sounds');

 const practiceApp=await launch({touch:false,reduced:true}),{game:pg,nodes:pn}=practiceApp;pg.station('practice');practiceApp.key('e');assert.equal(pn['window-title'].textContent,'Práctica de la Academia');assert.ok(pn.stage.querySelector('.challenge'));
 const answerCurrent=()=>{const view=pg.dialogue,answer=view.variant;switch(view.beat.kind){
  case 'mc':{const nodes=pn.stage.querySelectorAll('.option');for(let i=0;i<answer.answer;i++)practiceApp.key('ArrowDown');assert.equal(nodes[answer.answer].getAttribute('aria-pressed'),'true');practiceApp.key('e');break;}
  case 'numeric':{const input=pn.stage.querySelector('input');input.value=String(answer.answer);input.events.input();findText(pn.stage,'Comprobar respuesta →').click();break;}
  case 'order':{const list=pn.stage.querySelector('.order-list');for(let target=0;target<answer.items.length;target++){let at=list.children.findIndex(n=>n.textContent.includes(answer.items[target]));while(at>target){list.children[at].querySelectorAll('button')[0].click();at--;}}findText(pn.stage,'Comprobar orden →').click();break;}
  case 'match':{const columns=pn.stage.querySelectorAll('.match-column');for(const [left,right] of answer.pairs){columns[0].children.find(n=>n.textContent===left).click();columns[1].children.find(n=>n.textContent===right).click();}findText(pn.stage,'Comprobar parejas →').click();break;}
  case 'grid':{const svg=pn.stage.querySelector('.coordinate-grid');const chosen=svg.children.find(n=>n.getAttribute('aria-label')===`(${answer.answer[0]}, ${answer.answer[1]})`);chosen.click();findText(pn.stage,'Comprobar coordenadas →').click();break;}
  case 'reading':{pn.stage.querySelectorAll('.reading-question').forEach((node,i)=>node.querySelectorAll('.option')[answer.questions[i].answer].click());findText(pn.stage,'Comprobar respuestas →').click();break;}
 }};
 for(let i=0;i<3;i++){answerCurrent();assert.equal(pg.dialogue.resolved,true);assert.ok(pn.stage.querySelector('.feedback'));assert.equal(pg.state.tokens,60+2*(i+1));findText(pn.stage,'Continuar la práctica →').click();}assert.equal(pg.dialogue.type,'line');practiceApp.key('e');assert.equal(pn.overlay.hidden,true);console.log('✓ parchment practice preserves input handlers, success feedback, three challenges and exact two-ficha rewards');
 assert.ok(script.includes('estela_idle-71'));assert.equal(script.includes('estela_idle-72'),false);assert.ok(script.includes('objeto_medallon'));assert.ok(fs.statSync(__dirname+'/academia.html').size<12500000);
 console.log('UI lifecycle checks passed (DOM/Canvas shim; browser layout is not verified).');
})().catch(e=>{console.error(e);process.exitCode=1;});
